FROM maven:3-jdk-8-alpine as builder
WORKDIR /app
COPY . .
RUN ./burst.sh compile

FROM openjdk:8-jdk-alpine
RUN apk update && apk upgrade && apk add --no-cache bash
WORKDIR /app
COPY --from=builder /app/burst.jar .
VOLUME ["/etc/burstcoin/conf"]
COPY conf-mysql /etc/burstcoin/conf
EXPOSE 8125 8123
ENTRYPOINT ["java", "-classpath", "/app/burst.jar:/etc/burstcoin/conf", "-Ddev=1", "brs.Burst"]
