#!/bin/sh
set -e

case "$1" in
  upgrade)
    ;;

  purge)
    # Remove the user and db
    mysql -uroot -hlocalhost -e "DROP USER 'burst'@'localhost';DROP DATABASE burst;\q" > /dev/null 2>&1 || true
    rm -f /var/log/burstcoin.log*
    ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0

