#!/bin/sh
set -e

case "$1" in
  remove|deconfigure)
    # systemd: On uninstall (not upgrade), disable and stop the unit
    if [ -x /bin/systemctl ]; then
      systemctl --no-reload disable burstcoin.service >/dev/null 2>&1 || true
      systemctl stop burstcoin.service >/dev/null 2>&1 || true
    fi
    ;;

  failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0

